main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('contact/', views.contact_page, name='contact'),
    path('faq/', views.faq_page, name='faq'),
    path('blog/', views.blog_page, name='blog'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    thumbnail = models.ImageField(upload_to='thumbnails/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField(default=False)
    latestnews = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Zespol(models.Model):
    imienazwisko = models.CharField(max_length=50)
    pozycja = models.CharField(max_length=50)
    zdjecie = models.ImageField(upload_to='zespol/', null=True, blank=True)

    def __str__(self):
        return self.imienazwisko
    
class Mecze(models.Model):
    data = models.DateField()
    godzina = models.TimeField()
    gospodarz = models.CharField(max_length=100)
    logo_gospodarza = models.ImageField(upload_to='logos/')
    wynik = models.CharField(max_length=10, blank=True, null=True)  # Pole wyniku
    przeciwnik = models.CharField(max_length=100)
    logo_przeciwnika = models.ImageField(upload_to='logos/')

    @staticmethod
    def ostatni_mecz():
        return Mecze.objects.filter(wynik__isnull=False).order_by('-data').first()

    @staticmethod
    def najblizszy_mecz():
        return Mecze.objects.filter(data__gt=timezone.now()).order_by('data').first()

class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()

    def __str__(self):
        return self.question

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class ContactEntry(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return f"{self.name} - {self.email}"

main/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

main/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.mail import send_mail
from django.db.models import Q
from django.utils import timezone
from django.core.serializers import serialize
from .forms import ContactForm
from .models import ContactEntry,Mecze,Post,Zespol

def home_page(request):
    mecze = Mecze.objects.filter(data__gt=timezone.now()).order_by('data')
    mecze_json = serialize('json', mecze)

    # Znajdź najnowszy post oznaczony jako featured
    featured_post = Post.objects.filter(featured=True).order_by('-created_at').first()
    
    # Znajdź trzy najnowsze posty oznaczone jako latestnews
    latest_news = Post.objects.filter(latestnews=True).order_by('-created_at')[:4]

    # Zespol
    zespol = Zespol.objects.all()

    ostanieMecze = Mecze.objects.filter(Q(data__lt=timezone.now()) & ~Q(wynik=None)).order_by('-data')[:4]
    context = {
        'mecze': mecze,
        'mecze_json': mecze_json,
        'ostanieMecze' : ostanieMecze,
        'featured_post': featured_post,
        'latest_news': latest_news,
        'zespol': zespol
    }
    return render(request, 'main/home.html', context)


def faq_page(request):
    return render(request, 'main/faq.html')

def blog_page(request):
    # dodac ograniczenie na 16 postow maks 
    posts = Post.objects.order_by('-created_at')[:16]

    context = {
        'posts':posts
    }
    return render(request, 'main/blog.html', context)


def contact_page(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        # Sprawdzenie, czy wszystkie pola formularza są uzupełnione
        if name and email and message:
            # Zapisanie wpisu do bazy danych
            contact = ContactEntry.objects.create(
                name=name,
                email=email,
                message=message
            )

            # Wysłanie maila
            send_mail(
                f"Message from {name} - {email}",
                message,
                email,
                ['quaiza.dev@gmail.com'],
            )

            # Przekierowanie użytkownika na stronę główną po wysłaniu formularza
            return redirect('home')
    else:
        # Jeśli metoda żądania nie jest POST, utwórz pusty formularz
        form = ContactForm()

    # Renderowanie szablonu z formularzem
    return render(request, 'main/contact.html', {'form': form})

main/templates/main/blog.html
{% extends 'base.html' %} {% load static %} {% block content%}
<!--Najnowszy post-->
<section
  id="test"
  class="hero-background"
  style="{% if posts.0.thumbnail %}background-image: url('{{ posts.0.thumbnail.url }}');{% endif %}"
>
  <div
    class="container col-xxl-8 px-4 py-5"
    style="
      height: 900px;
      display: flex;
      flex-direction: column;
      align-items: end;
    "
  >
    <div class="row align-items-end g-5 py-5 h-100">
      <div class="col-lg-6 hero-post p-4">
        <h1 class="display-5 fw-bold lh-1 mb-3">{{ posts.0.title }}</h1>
        <p class="lead">{{ posts.0.content|truncatechars:200 }}</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          {% include 'main/modal.html' with post=posts.0 %}
        </div>
      </div>
    </div>
  </div>
</section>
<div class="navbar background-merge-down-hero">
  <a class="navbar-brand" href="/">
    <div class="row">
      <div style="height: 25px"></div>
    </div>
  </a>
</div>

<!--Pozostałe post-->
<div class="container py-4" style="margin-top: -45px">
  <div class="row gx-4">
    {% for post in posts|slice:"1:" %}
    <div class="col-lg-6 pb-4">
      <div class="card" style="box-shadow: 0 15px 15px rgba(0, 0, 0, 0.3)">
        <img
          class="featuredposts-sec-img"
          src="{{ post.thumbnail.url }}"
          alt="Thumbnail"
          height="300px"
        />
        <div class="card-body">
          <h4 class="mb-0">{{post.title}}</h4>
          <p class="card-text mb-auto">{{post.content |truncatechars:100}}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <button type="button" class="btn btn-link p-0">
                <i class="bi bi-hand-thumbs-up-fill"></i>
              </button>
            </div>
            <div class="mx-2">
              <span>+3</span>
            </div>
            <div>
              <button type="button" class="btn btn-link p-0">
                <i class="bi bi-hand-thumbs-down"></i>
              </button>
              <button type="button" class="btn btn-link p-0 mx-2">
                <i class="bi bi-share"></i>
              </button>
            </div>
            <div class="ml-auto">
              {% include 'main/modal.html' with post=post %}
            </div>
          </div>
        </div>
      </div>
    </div>
    {%endfor%}
  </div>
</div>
{% endblock %}

main/templates/main/contact.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section style="background-color: #002d68">
  <div class="container p-4">
    <h1 class="text-white">Contact Us</h1>
    <div class="row row-cols-2">
      <div class="col-8">
        <form method="post">
          <div class="row">
            {% csrf_token %}

            <label for="id_name" class="form-label text-white">Name</label>
            <input type="text" class="form-control" id="id_name" name="name" />

            <label for="id_email" class="form-label text-white">Email:</label>
            <input
              type="email"
              class="form-control"
              id="id_email"
              name="email"
            />

            <label for="id_message" class="form-label text-white"
              >Message</label
            >
            <textarea
              id="id_message"
              class="form-control"
              name="message"
              style="height: 300px"
            ></textarea>
            <div class="col d-flex justify-content-end">
              <button
                class="btn btn-light"
                style="margin-top: 5px"
                type="submit"
              >
                Wyślij
              </button>
            </div>
          </div>
        </form>
      </div>
      <div class="col-4">
        <h3 class="text-white">Vivamus iaculis dignissim rhoncus.</h3>
        <p class="text-white">
          Aliquam posuere erat non lacus sollicitudin varius. In eu arcu
          sollicitudin, efficitur turpis quis, posuere turpis. Phasellus lacus
          nisl, tincidunt non dolor eget, aliquet egestas felis. Integer in
          sapien vestibulum, eleifend est auctor, finibus turpis. Curabitur eget
          nisl ultrices, pharetra turpis ac, convallis nisl. Nunc quis sagittis
          mauris. Aenean congue euismod magna, sit amet vehicula lectus tempus
          nec. Aenean purus sapien, finibus sed magna a, placerat maximus
          tellus. Pellentesque porta sed quam eget lacinia.
        </p>
      </div>
    </div>
  </div>
</section>
<div class="navbar background-merge-down-hero">
  <a class="navbar-brand" href="/">
    <div class="row">
      <div style="height: 25px"></div>
    </div>
  </a>
</div>
<div style="min-height: 42vh"></div>

{% endblock %}

main/templates/main/faq.html
{% extends 'base.html' %}

{% block title %}
FAQ
{% endblock %}

{% block content %}
<h1>Frequently Asked Questions</h1>
<p>Here are some common questions and answers.</p>
{% endblock %}

main/templates/main/modal.html
<!-- templates/main/modal.html -->
<div
  class="modal fade"
  id="modal_{{ post.id }}"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <!-- Thumbnail Image -->
      {% if post.thumbnail %}
      <img
        src="{{ post.thumbnail.url }}"
        class="img-fluid"
        alt="{{ post.title }}"
        style="max-height: 600px; object-fit: cover"
      />
      {% endif %}

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ post.title }}</h5>
      </div>
      <div class="modal-body">{{ post.content }}</div>
      <!-- footer -->
      <div
        class="modal-footer d-flex justify-content-between align-items-center"
      >
        <div>
          <button type="button" class="btn btn-link p-0">
            <i class="bi bi-hand-thumbs-up-fill"></i>
          </button>
        </div>
        <div class="mx-2">
          <span>+3</span>
        </div>
        <div>
          <button type="button" class="btn btn-link p-0">
            <i class="bi bi-hand-thumbs-down"></i>
          </button>
          <button type="button" class="btn btn-link p-0 mx-2">
            <i class="bi bi-share"></i>
          </button>
        </div>
        <div class="ml-auto">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Zamknij
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Button to trigger modal -->

<a
  type="button"
  data-toggle="modal"
  data-target="#modal_{{ post.id }}"
  href="#"
  class="fw-bold d-flex"
  style="font-size: 20px"
  >Czytaj dalej...</a
>

templates/base copy.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}My Project{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">My Project</a>
      {% load static %}
      <div class="row"></div>
      <img
        width="30"
        height="30"
        class="d-inline-block align-top"
        src="{% static 'images/logo.svg' %}"
        alt="Logo"
      />
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact/">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/faq/">FAQ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/">Blog</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

<div class="row row-cols-2">
  <!-- kolumna OstatniMecz -->
  {% if ostatni_mecz %}
  <div class="col text-center">
    <h3>Ostatni mecz</h3>
    {{ ostatni_mecz.data|date:"d-m-Y" }} {{ ostatni_mecz.godzina|time:"H:i"}}
    <div class="container">
      <!-- rzad OstatniMecz -->
      <div
        class="row no-gutters row-cols-5 d-flex justify-content-center align-items-center"
      >
        <!-- kolumna GospodarzNazwa -->
        <div class="col d-none d-md-flex justify-content-end">
          <h4 style="margin-right: 5px">{{ostatni_mecz.gospodarz}}</h4>
        </div>
        <!-- kolumna GospodarzLogo -->
        <div class="col-3">
          <img
            src="{{ ostatni_mecz.logo_gospodarza.url }}"
            alt="Logo Gospodarza"
            class="img-fluid"
          />
        </div>
        <!-- kolumna Wynik -->
        <div class="col-md-auto test"><h3>{{ ostatni_mecz.wynik }}</h3></div>
        <!-- kolumna PrzeciwnikLogo -->
        <div class="col-3">
          <img
            src="{{ ostatni_mecz.logo_przeciwnika.url }}"
            alt="Logo Gospodarza"
            class="img-fluid"
          />
        </div>
        <!-- kolumna PrzeciwnikNazwa -->
        <div class="col d-none d-md-flex justify-content-start">
          <h4 style="margin-left: 5px">{{ostatni_mecz.przeciwnik}}</h4>
        </div>
      </div>
    </div>
    {% else %}
    <p>Brak danych o ostatnim meczu.</p>
    {% endif %}
  </div>
  <!-- kolumna OstatniMecz -->
  {% if ostatni_mecz %}
  <div class="col text-center">
    <h3>Ostatni mecz</h3>
    {{ ostatni_mecz.data|date:"d-m-Y" }} {{ ostatni_mecz.godzina|time:"H:i"}}
    <div class="container">
      <!-- rzad OstatniMecz -->
      <div
        class="row no-gutters row-cols-5 d-flex justify-content-center align-items-center"
      >
        <!-- kolumna GospodarzNazwa -->
        <div class="col d-none d-md-flex justify-content-end">
          <h4 style="margin-right: 5px">{{ostatni_mecz.gospodarz}}</h4>
        </div>
        <!-- kolumna GospodarzLogo -->
        <div class="col-3">
          <img
            src="{{ ostatni_mecz.logo_gospodarza.url }}"
            alt="Logo Gospodarza"
            class="img-fluid"
          />
        </div>
        <!-- kolumna Wynik -->
        <div class="col-md-auto test"><h3>{{ ostatni_mecz.wynik }}</h3></div>
        <!-- kolumna PrzeciwnikLogo -->
        <div class="col-3">
          <img
            src="{{ ostatni_mecz.logo_przeciwnika.url }}"
            alt="Logo Gospodarza"
            class="img-fluid"
          />
        </div>
        <!-- kolumna PrzeciwnikNazwa -->
        <div class="col d-none d-md-flex justify-content-start">
          <h4 style="margin-left: 5px">{{ostatni_mecz.przeciwnik}}</h4>
        </div>
      </div>
    </div>
    {% else %}
    <p>Brak danych o ostatnim meczu.</p>
    {% endif %}
  </div>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}My Project{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css"
    />
    <!-- Montserrat Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
      rel="stylesheet"
    />

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <!-- Main Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-fixed-top navbar1">
      <a class="navbar-brand" href="/">
        <div class="row">
          <img
            width="70"
            height="70"
            src="{% static 'images/logo2_white.svg' %}"
            alt="Logo"
          />
          <h1 class="logo-text">BYU</h1>
        </div>
      </a>
      <!-- Przycisk do rozwijania na urządzeniach mobilnych -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Zawartość menu -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact/">Contact</a>
          </li>
        </ul>
      </div>
    </nav>
    <!-- Navbar End - \/ Content here \/ -->
    {% block content %} {% endblock %}
    <!-- Footer Start - /\ Content here /\ -->
    <footer class="footer bg-dark text-white">
      <div
        class="container-custom d-flex justify-content-between align-items-center py-3 border-highlight"
      >
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="me-2 text-muted text-decoration-none">
            <i class="bi bi-cup"></i>
            <span>&copy; 2024 Quaiza</span>
          </a>
        </div>

        <ul
          class="nav col-md-4 justify-content-end list-unstyled d-flex text-white"
        >
          <li class="ms-3 mr-3">
            <a class="text-muted" href="#"><i class="bi bi-twitter"></i></a>
          </li>
          <li class="ms-3 mr-3">
            <a class="text-muted" href="#"><i class="bi bi-instagram"></i></a>
          </li>
          <li class="ms-3 mr-3">
            <a class="text-muted" href="#"><i class="bi bi-facebook"></i></a>
          </li>
        </ul>
      </div>
    </footer>
    <!-- Footer End -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>